name: Gradle Build and Deploy
#https://github.com/gradle/gradle-build-action
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 8
      - uses: gradle/gradle-build-action@v2
        with:
          gradle-version: release-candidate
      - run: gradle bootjar
        
      - name: Show build libs
        run: ls -al ./build/libs
        shell: bash
#       - name: Deploy
#         uses: wlixcc/SFTP-Deploy-Action@v1.2.4
#         with:
#             username: 'root'
#             server: 'your server ip'
#             ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }} 
#             #password: 
#             local_path: './static/*'
#             remote_path: '/var/www/app'
#             sftpArgs: '-o ConnectTimeout=5'
#       - name: Execute remote shell
#         uses: appleboy/ssh-action@master
#         with:
#           host: ${{ secrets.HOST }}
#           username: ${{ secrets.USERNAME }}
#           key: ${{ secrets.KEY }}
#           port: ${{ secrets.PORT }}
#           script: |
#             cd git/swlabs-helper
#             sh deploy.sh
